FROM jenkins/jenkins:2.467-jdk21
USER root

ARG DOCKER_GID=138

RUN mkdir /var/jenkins_home/.kube && \
    mkdir /var/jenkins_home/.aws
#COPY kubeconfig /var/jenkins_home/.kube/

# Install Docker CLI, gradle and curl, gnupg
RUN apt-get update && \
    apt-get install -y docker.io \
                       gradle \
                       nodejs \
                       npm

# Install kubectl
RUN curl -LO https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl && \
install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
#ENV KUBECONFIG=/var/jenkins_home/.kube/kubeconfig

#install aws-iam-authenticator
RUN curl -Lo aws-iam-authenticator https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.6.11/aws-iam-authenticator_0.6.11_linux_amd64 && \
chmod +x ./aws-iam-authenticator && \
mv ./aws-iam-authenticator /usr/local/bin 


RUN sed -i "s/docker:x:[0-9]*/docker:x:${DOCKER_GID}/" /etc/group && \
    usermod -aG docker jenkins

USER jenkins